package dev.vality.fraudbusters.api.exceptions;

public class RemoteInvocationException extends RuntimeException {

    public RemoteInvocationException(Throwable cause) {
        super(cause);
    }
}
